/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
#define YALS_OS "Linux code-server 5.15.74-1-pve x86_64"
#define YALS_COMPILED "Mon Jul  8 07:46:21 UTC 2024"
#define YALS_RELEASED "Fr 1. Mär 05:17:48 CET 2019"
#define YALS_VERSION "03v"
#define YALS_ID "b1316746d40f72f147cde3f4ec54fadbe0730427"
